import './globals.css'
import { Open_Sans, Cormorant_Upright, Sacramento } from 'next/font/google'

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--openSans'
})

const sacramento = Sacramento({
  subsets: ['latin'],
  variable: '--sacramento',
  weight: '400'
})

const comorant = Cormorant_Upright({
  subsets: ['latin'],
  variable: '--comorant',
  weight: ['400', '600', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${openSans.variable} ${sacramento.variable} ${comorant.variable}`} lang="en">
      <body>{children}</body>
    </html>
  )
}
